version: "3.8"

services:
  db:
    image: postgres:15
    container_name: task-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./com.desafio.taskmanager
      dockerfile: src/main/docker/Dockerfile
    container_name: task-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/taskdb
      QUARKUS_DATASOURCE_USERNAME: taskuser
      QUARKUS_DATASOURCE_PASSWORD: taskpassword
    networks:
      - task-net

volumes:
  postgres-data:

networks:
  task-net:
